site_name: Go Notes
repo_url: https://github.com/Lixfeld/go-notes
repo_name: GitHub Source

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    logo: material/note
  features:
    - content.code.copy

  palette:
    - scheme: slate
      primary: light blue

# syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - Basics:
    - basics/helloworld.md
    - basics/keywords.md
    - basics/visibility.md
    - basics/data_types.md
    - basics/variables.md
    - basics/constants.md
    - basics/conversions.md
    - basics/functions.md
    - basics/loops.md
    - basics/if_statements.md
    - basics/switch.md
    - basics/pointers.md
  - Types:
    - types/arrays.md
    - types/slices.md
    - types/maps.md
    - types/named_types.md
    - types/structs.md
    - types/methods.md
    - types/interfaces.md
  - Packages:
      - builtin: packages/builtin.md
      - fmt: packages/fmt.md
      - slices: packages/slices.md
      - strconv: packages/strconv.md
      - strings: packages/strings.md
      - unicode: packages/unicode.md
