site_name: Go Notes
repo_url: https://github.com/Lixfeld/go-notes
repo_name: GitHub Source

extra_css:
  - stylesheets/extra.css

theme:
  name: material
  icon:
    logo: material/note
  features:
    - content.code.copy

  palette:
    - scheme: slate
      primary: light blue

# syntax highlighting
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - helloworld.md
  - keywords.md
  - visibility.md
  - types.md
  - variables.md
  - constants.md
  - conversions.md
  - functions.md
  - loops.md
  - if_statements.md
  - switch.md
  - arrays.md
  - slices.md
  - maps.md
  - named_types.md
  - pointers.md
  - structs.md
  - Packages:
      - fmt: packages/fmt.md
      - slices: packages/slices.md
      - unicode: packages/unicode.md
